baseURL = 'https://harshitc.me/'
defaultContentLanguage = 'en'
title = 'Harshit :)'
disableKinds = ['taxonomy', 'term']
buildFuture = true

[params]
  author = 'Harshit'
  description = 'professional dumbass.'
  logo_text = 'Harshit'
  logo_dot = ':)'
  footer_text = 'brought to you by a lot of chicken'
  github_url = 'https://github.com/harshyeet'
  primary_email = 'hershitt@proton.me'
  secondary_email = 'hershhitt@gmail.com'
  twitter_handle = '@hershhitt'
  twitter_url = 'https://x.com/hershhitt'
  pgp_key_path = 'pgp_key.txt.asc'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = 'monokai'
